# Generated by Django 5.1.6 on 2025-05-07 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0007_click_dislikes_click_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='disliked_by',
            field=models.ManyToManyField(blank=True, related_name='disliked_clicks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='click',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_clicks', to=settings.AUTH_USER_MODEL),
        ),
    ]
