# Generated by Django 5.1.6 on 2025-05-07 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0008_click_disliked_by_click_liked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='click_images/'),
        ),
        migrations.AlterField(
            model_name='click',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to=settings.AUTH_USER_MODEL),
        ),
    ]
