# Generated by Django 5.1.6 on 2025-05-14 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickerapp', '0009_click_image_alter_click_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='click',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='click_videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
